name = "VectorBijectorsTest"
uuid = "5b3bcb54-8207-46b2-8895-8bbf15b6d072"
authors = ["Penelope Yong <penelopeysm@gmail.com>"]
version = "0.1.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VectorBijectors = "8f4f62c7-8ad6-4a10-ba5f-dd81de6324a2"

[sources]
VectorBijectors = {path = "../VectorBijectors"}

[compat]
ADTypes = "1.19"
DifferentiationInterface = "0.7"
Distributions = "0.25"
ForwardDiff = "1"
LinearAlgebra = "1"
Test = "1"
