name: CI (VectorBijectors)

on:
  push:
    branches:
      - main
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

# Cancel existing tests on the same PR if a new commit is added to a pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/main' }}

jobs:
  test:
    runs-on: ${{ matrix.runner.os }}
    strategy:
      fail-fast: false

      matrix:
        runner:
          # Ubuntu
          - version: '1'
            os: ubuntu-latest
          # Windows
          - version: '1'
            os: windows-latest
          # macOS
          - version: '1'
            os: macos-latest
          # Minimum supported version
          - version: 'min'
            os: ubuntu-latest
          # 1.11
          - version: '1.11'
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.runner.version }}
          project: ./VectorBijectors

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: ./VectorBijectors

      - uses: julia-actions/julia-runtest@v1
        with:
          project: ./VectorBijectors
